name = "sistema-coletas"
compatibility_date = "2024-03-20"
compatibility_flags = [ "nodejs_compat" ]
pages_build_output_dir = "out"

[[d1_databases]]
binding = "DB"
database_name = "coletas"
database_id = "fd04147f-1047-438e-b5d6-76b9bfa92061"
